# Ensure BotFramework-Streaming library works in the browser by running tests after:
# - deploying a streaming-enabled JS Echo Bot 
# - and a React App that uses latest streaming bits in DLJS and WebChat

name: $(Build.BuildId)
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

variables:
  ReactProjectDir: $(System.DefaultWorkingDirectory)/pipeline2-with-yarnlock
  runCodesignValidationInjection: false

stages:
  - stage: Create_And_Deploy_Projects
    jobs:
        - job: Prep_React_App
          steps:
            - task: Cache@2
              displayName: Cache npm
              inputs:
                key: 'test-pipeline-cache-yarnlock2 | npm | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/pipeline2-with-yarnlock/yarn.lock'
                path: $(ReactProjectDir)/node_modules
                cacheHitVar: 'CacheRestored'
            
            - powershell: yarn install
              displayName: 'yarn install react-app'
              condition: ne(variables.CacheRestored, 'true')
              workingDirectory: $(ReactProjectDir)
            
            - task: PublishPipelineArtifact@1
              displayName: 'Publish Artifact: CustomizedReactApp'
              inputs:
                targetPath: $(ReactProjectDir)
                artifactName: 'CustomizedReactApp'

        - job: Run_Tests
          dependsOn: Prep_React_App
          condition: succeeded()
          variables:
            PORT: 3009
          steps:
            - powershell: yarn install
              displayName: 'yarn install tests'
              condition: ne(variables.CacheRestored, 'true')
              workingDirectory: $(System.DefaultWorkingDirectory)/tests
            
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: CustomizedReactApp
                path: $(ReactProjectDir)
            
            - powershell: start powershell {npx react-scripts start}
              displayName: 'npm start React App'
              workingDirectory: $(ReactProjectDir)
            
            - powershell: Start-Sleep -Seconds 60
              displayName: 'Sleeping for 60 seconds to allow React App to serve...'
            
            - powershell: npm test
              displayName: 'npm test'
              workingDirectory: $(System.DefaultWorkingDirectory)/tests

          
